export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  rating: number;
  reviews: number;
  category: string;
  colors: string[];
  inStock: boolean;
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Harmony Gold Beaded Bracelet',
    description: 'A stunning combination of gold and amber clay beads with traditional African patterns. Perfect for daily wear or special occasions.',
    price: 2800,
    image: '/products/bracelet-1.jpg',
    rating: 5,
    reviews: 148,
    category: 'Bracelets',
    colors: ['Gold', 'Amber'],
    inStock: true,
  },
  {
    id: '2',
    name: 'Serengeti Collection Bracelet',
    description: 'Inspired by the vast landscapes of Africa. Features earth tones with turquoise accents and handcrafted clay beads.',
    price: 3200,
    image: '/products/bracelet-2.jpg',
    rating: 5,
    reviews: 92,
    category: 'Bracelets',
    colors: ['Earth Brown', 'Turquoise'],
    inStock: true,
  },
  {
    id: '3',
    name: 'Ndoto Dream Bracelet',
    description: 'A beautiful blend of glass and clay beads celebrating African artistry. Each bead is uniquely hand-painted.',
    price: 3500,
    image: '/products/bracelet-3.jpg',
    rating: 4.5,
    reviews: 156,
    category: 'Bracelets',
    colors: ['Multicolor', 'Gold'],
    inStock: true,
  },
  {
    id: '4',
    name: 'Ujumbe Heritage Strand',
    description: 'Traditional African-inspired beaded strand featuring natural clay beads with intricate carving details and cultural symbolism.',
    price: 2500,
    image: '/products/bracelet-4.jpg',
    rating: 5,
    reviews: 203,
    category: 'Bracelets',
    colors: ['Orange', 'Gold', 'Brown'],
    inStock: true,
  },
  {
    id: '5',
    name: 'Kusafiri Traveler Bangles',
    description: 'A set of layered bracelets combining African and Indian design elements. Perfect for creating your unique style.',
    price: 4200,
    image: '/products/bracelet-5.jpg',
    rating: 4.5,
    reviews: 87,
    category: 'Bracelets',
    colors: ['Mixed', 'Gold'],
    inStock: true,
  },
  {
    id: '6',
    name: 'Zawadi Gift Bracelet',
    description: 'A thoughtfully designed bracelet that makes a perfect gift. Features warm earth tones and comfortable fit.',
    price: 2200,
    image: '/products/bracelet-1.jpg',
    rating: 5,
    reviews: 167,
    category: 'Bracelets',
    colors: ['Beige', 'Gold'],
    inStock: true,
  },
  {
    id: '7',
    name: 'Rafiki Connection Set',
    description: 'Friendship bracelets inspired by African friendship traditions. Set includes two matching bracelets.',
    price: 4500,
    image: '/products/bracelet-2.jpg',
    rating: 4.5,
    reviews: 124,
    category: 'Bracelets',
    colors: ['Gold', 'Amber', 'Coral'],
    inStock: true,
  },
  {
    id: '8',
    name: 'Asante Gratitude Bracelet',
    description: 'Handwoven beads with artistic glass elements. A tribute to African craftsmanship and gratitude.',
    price: 3800,
    image: '/products/bracelet-3.jpg',
    rating: 5,
    reviews: 178,
    category: 'Bracelets',
    colors: ['Purple', 'Gold', 'Amber'],
    inStock: true,
  },
  {
    id: '9',
    name: 'Copper Heritage Collection',
    description: 'Featuring authentic copper and gold beads with traditional African geometric patterns handcrafted on woven textile.',
    price: 2900,
    image: '/products/bracelet-6.jpg',
    rating: 4.5,
    reviews: 134,
    category: 'Bracelets',
    colors: ['Copper', 'Gold', 'Bronze'],
    inStock: true,
  },
  {
    id: '10',
    name: 'Amara Layered Set',
    description: 'Perfect for stacking. A set of three complementary bracelets designed to work beautifully together or separately.',
    price: 5200,
    image: '/products/bracelet-7.jpg',
    rating: 5,
    reviews: 156,
    category: 'Bracelets',
    colors: ['Mixed Warm Tones'],
    inStock: true,
  },
  {
    id: '11',
    name: 'Rainbow Harmony Bracelet',
    description: 'A vibrant collection of colorful handmade beads featuring Indian and African designs in coral and turquoise.',
    price: 3400,
    image: '/products/bracelet-8.jpg',
    rating: 4.5,
    reviews: 98,
    category: 'Bracelets',
    colors: ['Coral', 'Turquoise', 'Gold'],
    inStock: true,
  },
  {
    id: '12',
    name: 'Marble Elegance Collection',
    description: 'Premium beaded bracelets with gold accents displayed on elegant marble, perfect for luxury jewelry lovers.',
    price: 4100,
    image: '/products/bracelet-9.jpg',
    rating: 5,
    reviews: 142,
    category: 'Bracelets',
    colors: ['Gold', 'Earth Tones', 'Bronze'],
    inStock: true,
  },
  {
    id: '13',
    name: 'Artisan\'s Touch Bracelet',
    description: 'Handcrafted using traditional techniques by talented African artisans. Each piece tells a story of heritage and craftsmanship.',
    price: 3600,
    image: '/products/bracelet-10.jpg',
    rating: 4.5,
    reviews: 167,
    category: 'Bracelets',
    colors: ['Natural', 'Clay', 'Earthy'],
    inStock: true,
  },
];

export interface CartItem extends Product {
  quantity: number;
}
