import prisma from '@/lib/db/prisma';

// Initial products to seed
const initialProducts = [
  {
    name: 'Harmony Gold Beaded Bracelet',
    description: 'A stunning combination of gold and amber clay beads with traditional African patterns. Perfect for daily wear or special occasions.',
    price: 2800,
    costPrice: 1200,
    sku: 'BRACELET-001',
    category: 'Bracelets',
    colors: ['Gold', 'Amber'],
    sizes: ['M', 'L'],
    images: ['/products/bracelet-1.jpg'],
    stock: 25,
    lowStockAlert: 5,
    slug: 'harmony-gold-beaded-bracelet',
    rating: 5,
    reviewCount: 148,
    inStock: true,
    isActive: true,
    isFeatured: true,
    metaTitle: 'Harmony Gold Beaded Bracelet - Handcrafted African Jewelry',
    metaDescription: 'Stunning gold and amber clay beads bracelet with traditional African patterns. Shop now for authentic handcrafted jewelry.',
  },
  {
    name: 'Serengeti Collection Bracelet',
    description: 'Inspired by the vast landscapes of Africa. Features earth tones with turquoise accents and handcrafted clay beads.',
    price: 3200,
    costPrice: 1400,
    sku: 'BRACELET-002',
    category: 'Bracelets',
    colors: ['Earth Brown', 'Turquoise'],
    sizes: ['M', 'L', 'XL'],
    images: ['/products/bracelet-2.jpg'],
    stock: 18,
    lowStockAlert: 5,
    slug: 'serengeti-collection-bracelet',
    rating: 5,
    reviewCount: 92,
    inStock: true,
    isActive: true,
    isFeatured: true,
    metaTitle: 'Serengeti Collection Bracelet',
    metaDescription: 'Earth tones with turquoise accents. Handcrafted clay beads inspired by African landscapes.',
  },
  {
    name: 'Ndoto Dream Bracelet',
    description: 'A beautiful blend of glass and clay beads celebrating African artistry. Each bead is uniquely hand-painted.',
    price: 3500,
    costPrice: 1600,
    sku: 'BRACELET-003',
    category: 'Bracelets',
    colors: ['Multicolor', 'Gold'],
    sizes: ['S', 'M', 'L'],
    images: ['/products/bracelet-3.jpg'],
    stock: 15,
    lowStockAlert: 5,
    slug: 'ndoto-dream-bracelet',
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    isActive: true,
    isFeatured: true,
    metaTitle: 'Ndoto Dream Bracelet - Hand-painted Glass & Clay',
    metaDescription: 'Hand-painted glass and clay beads celebrating African artistry. Unique designs.',
  },
  {
    name: 'Maasai Warrior Bracelet',
    description: 'Inspired by traditional Maasai beading techniques. Red and blue beads with intricate patterns representing strength and courage.',
    price: 2600,
    costPrice: 1100,
    sku: 'BRACELET-004',
    category: 'Bracelets',
    colors: ['Red', 'Blue'],
    sizes: ['M', 'L'],
    images: ['/products/bracelet-4.jpg'],
    stock: 30,
    lowStockAlert: 5,
    slug: 'maasai-warrior-bracelet',
    rating: 4.8,
    reviewCount: 204,
    inStock: true,
    isActive: true,
    isFeatured: false,
    metaTitle: 'Maasai Warrior Bracelet',
    metaDescription: 'Traditional Maasai beading techniques with red and blue beads.',
  },
  {
    name: 'Swahili Sunset Bracelet',
    description: 'Warm sunset colors blend beautifully in this bracelet. Orange, yellow, and red clay beads evoke the beauty of coastal East Africa.',
    price: 2900,
    costPrice: 1300,
    sku: 'BRACELET-005',
    category: 'Bracelets',
    colors: ['Orange', 'Yellow', 'Red'],
    sizes: ['M', 'L', 'XL'],
    images: ['/products/bracelet-5.jpg'],
    stock: 22,
    lowStockAlert: 5,
    slug: 'swahili-sunset-bracelet',
    rating: 4.9,
    reviewCount: 178,
    inStock: true,
    isActive: true,
    isFeatured: true,
    metaTitle: 'Swahili Sunset Bracelet',
    metaDescription: 'Warm sunset colors inspired by East African coastlines.',
  },
  {
    name: 'Kente Kente Bracelet',
    description: 'Inspired by traditional kente cloth patterns from Ghana. Vibrant colors and intricate geometric designs.',
    price: 3800,
    costPrice: 1700,
    sku: 'BRACELET-006',
    category: 'Bracelets',
    colors: ['Multicolor'],
    sizes: ['M', 'L'],
    images: ['/products/bracelet-6.jpg'],
    stock: 12,
    lowStockAlert: 5,
    slug: 'kente-kente-bracelet',
    rating: 5,
    reviewCount: 87,
    inStock: true,
    isActive: true,
    isFeatured: true,
    metaTitle: 'Kente Kente Bracelet - Traditional Ghanaian Patterns',
    metaDescription: 'Vibrant kente cloth-inspired patterns. Handcrafted beads with geometric designs.',
  },
  {
    name: 'Zulu Beaded Bracelet',
    description: 'Classic South African Zulu beadwork design. Black and white geometric patterns on a sturdy foundation.',
    price: 3100,
    costPrice: 1350,
    sku: 'BRACELET-007',
    category: 'Bracelets',
    colors: ['Black', 'White'],
    sizes: ['M', 'L', 'XL'],
    images: ['/products/bracelet-7.jpg'],
    stock: 19,
    lowStockAlert: 5,
    slug: 'zulu-beaded-bracelet',
    rating: 4.7,
    reviewCount: 145,
    inStock: true,
    isActive: true,
    isFeatured: false,
    metaTitle: 'Zulu Beaded Bracelet - South African Craftsmanship',
    metaDescription: 'Classic South African Zulu beadwork. Black and white geometric patterns.',
  },
  {
    name: 'Adire Indigo Bracelet',
    description: 'Nigerian-inspired indigo and cream beads creating a classic monochrome aesthetic. Perfect for both casual and formal wear.',
    price: 2700,
    costPrice: 1200,
    sku: 'BRACELET-008',
    category: 'Bracelets',
    colors: ['Indigo', 'Cream'],
    sizes: ['S', 'M', 'L'],
    images: ['/products/bracelet-8.jpg'],
    stock: 28,
    lowStockAlert: 5,
    slug: 'adire-indigo-bracelet',
    rating: 4.6,
    reviewCount: 119,
    inStock: true,
    isActive: true,
    isFeatured: false,
    metaTitle: 'Adire Indigo Bracelet - Nigerian Textile Inspired',
    metaDescription: 'Nigerian-inspired indigo and cream beads. Versatile monochrome aesthetic.',
  },
  {
    name: 'Ethiopian Opal Bracelet',
    description: 'Featuring luminous opal-colored beads with gold accents. A luxurious choice inspired by Ethiopian gemstone traditions.',
    price: 4200,
    costPrice: 1900,
    sku: 'BRACELET-009',
    category: 'Bracelets',
    colors: ['Opal', 'Gold'],
    sizes: ['M', 'L'],
    images: ['/products/bracelet-9.jpg'],
    stock: 10,
    lowStockAlert: 5,
    slug: 'ethiopian-opal-bracelet',
    rating: 5,
    reviewCount: 76,
    inStock: true,
    isActive: true,
    isFeatured: true,
    metaTitle: 'Ethiopian Opal Bracelet - Luxury Gemstone Inspired',
    metaDescription: 'Luminous opal-colored beads with gold accents. Inspired by Ethiopian gemstones.',
  },
  {
    name: 'Ndebele Art Bracelet',
    description: 'Bold geometric patterns inspired by South African Ndebele art. Bright primary colors create a striking visual impact.',
    price: 3400,
    costPrice: 1500,
    sku: 'BRACELET-010',
    category: 'Bracelets',
    colors: ['Multicolor'],
    sizes: ['M', 'L'],
    images: ['/products/bracelet-10.jpg'],
    stock: 14,
    lowStockAlert: 5,
    slug: 'ndebele-art-bracelet',
    rating: 4.8,
    reviewCount: 133,
    inStock: true,
    isActive: true,
    isFeatured: true,
    metaTitle: 'Ndebele Art Bracelet - Bold Geometric Patterns',
    metaDescription: 'Bold geometric patterns inspired by South African Ndebele art.',
  },
  {
    name: 'Shona Stone Bracelet',
    description: 'Smooth polished stone beads from Zimbabwe combined with clay elements. A natural and earthy design.',
    price: 3300,
    costPrice: 1450,
    sku: 'BRACELET-011',
    category: 'Bracelets',
    colors: ['Earthy Tones'],
    sizes: ['M', 'L', 'XL'],
    images: ['/products/bracelet-11.jpg'],
    stock: 16,
    lowStockAlert: 5,
    slug: 'shona-stone-bracelet',
    rating: 4.5,
    reviewCount: 98,
    inStock: true,
    isActive: true,
    isFeatured: false,
    metaTitle: 'Shona Stone Bracelet - Natural Zimbabwe Craftsmanship',
    metaDescription: 'Smooth polished stone beads combined with clay. Natural earthy design.',
  },
  {
    name: 'Kenyan Tribal Fusion Bracelet',
    description: 'Modern fusion of traditional Kenyan tribal patterns with contemporary design elements. Unique and versatile.',
    price: 3600,
    costPrice: 1600,
    sku: 'BRACELET-012',
    category: 'Bracelets',
    colors: ['Multicolor', 'Gold'],
    sizes: ['S', 'M', 'L'],
    images: ['/products/bracelet-12.jpg'],
    stock: 20,
    lowStockAlert: 5,
    slug: 'kenyan-tribal-fusion-bracelet',
    rating: 4.9,
    reviewCount: 167,
    inStock: true,
    isActive: true,
    isFeatured: true,
    metaTitle: 'Kenyan Tribal Fusion Bracelet - Modern Meets Traditional',
    metaDescription: 'Modern fusion of traditional Kenyan patterns with contemporary design.',
  },
];

async function seed() {
  console.log('🌱 Starting database seed...');

  try {
    // Clear existing products
    await prisma.product.deleteMany({});
    console.log('✓ Cleared existing products');

    // Create admin user
    const adminUser = await prisma.user.upsert({
      where: { email: 'admin@ajabubeads.com' },
      update: { isAdmin: true, isSuperAdmin: true } as any,
      create: {
        email: 'admin@ajabubeads.com',
        name: 'Admin User',
        password: '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36CH5s36', // hashed "admin123"
        phone: '+254 712 345 678',
        country: 'Kenya',
        isActive: true,
        isAdmin: true,
        isSuperAdmin: true,
      } as any,
    });
    console.log('✓ Created/updated admin user:', adminUser.email);

    // Seed products
    const createdProducts = await prisma.product.createMany({
      data: initialProducts,
      skipDuplicates: true,
    });
    console.log(`✓ Created ${createdProducts.count} products`);

    console.log('✅ Database seeding complete!');
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

seed();
